// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgh9ys12UucB5g2by5bMQJnQJMmRx44sM',
    appId: '1:228402230352:android:5d43d93236e4162246cd55',
    messagingSenderId: '228402230352',
    projectId: 'danbeauty-937c5',
    databaseURL: 'https://danbeauty-937c5-default-rtdb.firebaseio.com',
    storageBucket: 'danbeauty-937c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_awcBKxIFn0nUxl-G0lk8eDL9-OWxYI',
    appId: '1:228402230352:ios:8bf2ca7788a0158f46cd55',
    messagingSenderId: '228402230352',
    projectId: 'danbeauty-937c5',
    databaseURL: 'https://danbeauty-937c5-default-rtdb.firebaseio.com',
    storageBucket: 'danbeauty-937c5.appspot.com',
    androidClientId: '228402230352-1tn0co2ikil8ldbua6mqoedbqehtesfq.apps.googleusercontent.com',
    iosClientId: '228402230352-cc66hc93lqgliqtq4k7oln6eup68ndcs.apps.googleusercontent.com',
    iosBundleId: 'com.diesel.customer',
  );

}